# Generated by Django 5.0.4 on 2024-07-11 06:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0003_leaverequest_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaverequest',
            name='leavetype',
            field=models.ForeignKey(default='4e701692-cd68-4fea-9e4d-6945ef193cc0', on_delete=django.db.models.deletion.CASCADE, related_name='leave_requests', to='employee.leavetype'),
            preserve_default=False,
        ),
    ]
